#!/usr/bin/env groovy

node('rhel8') {
    stage('Checkout repo') {
        deleteDir()
        git url: "https://github.com/${params.FORK}/vscode-openshift-tools.git", branch: "${params.BRANCH}"
    }

    stage('Install requirements') {
        def nodeHome = tool 'nodejs-lts'
        env.PATH="${env.PATH}:${nodeHome}/bin"
        sh "npm install"
    }

    withEnv(['JUNIT_REPORT_PATH=report.xml']) {
        stage('UI smoke test') {
            wrap([$class: 'Xvnc']) {
                sh "npm run smoke-test"
                junit 'report.xml'
            }
        }
    }
}