#!/usr/bin/env groovy

node('rhel8') {
    stage('Checkout repo') {
        deleteDir()
        git url: "https://github.com/${params.FORK}/vscode-openshift-tools.git", branch: "${params.BRANCH}"
    }

    stage('Install requirements') {
        def nodeHome = tool 'nodejs-lts'
        env.PATH="${env.PATH}:${nodeHome}/bin"
        sh "npm install"
    }

    withEnv(['JUNIT_REPORT_PATH=report.xml']) {
        stage('integration tests') {
            catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                wrap([$class: 'Xvnc']) {
                sh "npm run test-integration"
                junit 'report.xml'
                }
            }
        }
        stage('cluster-dependent UI tests') {
            wrap([$class: 'Xvnc']) {
                sh "npm run cluster-ui-test"
                junit 'report.xml'
            }
        }
    }
}
