#!/usr/bin/env groovy

node('rhel8') {
    stage('Checkout repo') {
        deleteDir()
        git url: "https://github.com/${params.FORK}/vscode-openshift-tools.git", branch: "${params.BRANCH}"
    }

    stage('Install requirements') {
        def nodeHome = tool 'nodejs-18.15.0'
        env.PATH="${env.PATH}:${nodeHome}/bin"
        sh "npm install"
    }

    withEnv(['JUNIT_REPORT_PATH=report.xml']) {
        stage('integration tests') {
            catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                wrap([$class: 'Xvnc']) {
                sh "IS_OPENSHIFT=1 npm run test-integration"
                junit 'report.xml'
                }
            }
        }
        withEnv(['PATH+EXTRA=' + pwd()]){
            stage('cluster-dependent UI tests') {
                catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                    wrap([$class: 'Xvnc']) {
                        sh 'curl -L -o $(pwd)/kubectl "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"'
                        sh 'chmod +x kubectl'
                        sh "npm run cluster-ui-test"
                        junit 'report.xml'
                    }
                }
            }
        }
        stage('Archive Artifacts'){
            archiveArtifacts artifacts: '/tmp/test-resources/screenshots/*', allowEmptyArchive: true
        }
    }
}
