name: check-kn-client

on: [workflow_dispatch]

jobs:
  check-kn-client-repo:
    runs-on: ubuntu-latest
    env:
        TOOL_REPO: knative/client
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3
      - name: Get latest knative client version
        run: |
          echo "REPO_KN_CLIENT_VERSION=$(cat src/tools.json | jq -r .kn.version)" >> $GITHUB_ENV
          LATEST_TOOL_RELEASE_RESP=$(gh release --repo ${{ env.TOOL_REPO }} view --json tagName,url)
          echo "LATEST_TOOL_RELEASE=$(echo ${LATEST_TOOL_RELEASE_RESP} | jq -r .tagName | sed 's|knative-v||')" >> $GITHUB_ENV
          echo "LATEST_TOOL_URL=$(echo ${LATEST_TOOL_RELEASE_RESP} | jq -r .url)" >> $GITHUB_ENV
      - name: Find existing PR for knative client version
        run: |
          echo PR_EXISTS=$(gh pr --repo ${{ github.repository }} list --state all --search "update kn client ${{env.LATEST_TOOL_RELEASE}} in:title" --json url | jq length) >> $GITHUB_ENV
      - name: Update src/tools.json with latest knatve client version
        if: ${{ (env.LATEST_TOOL_RELEASE != env.REPO_KN_CLIENT_VERSION) && (env.PR_EXISTS == 0) }}
        run: |
          old_checkSum_url=`jq -r .kn.cheksumURL src/tools.json`
          new_checksum_url=`echo ${old_checkSum_url} | sed "s|${{ env.REPO_KN_CLIENT_VERSION }}|${{ env.LATEST_TOOL_RELEASE }}|"`
          jq --indent 4 '.kn.version = "${{ env.LATEST_TOOL_RELEASE }}"' src/tools.json | jq --indent 4 '.kn.versionRange = "^${{ env.LATEST_TOOL_RELEASE }}"' | jq --indent 4 '.kn.versionRangeLabel = "version >= ${{ env.LATEST_TOOL_RELEASE }}"' | jq --indent 4 '.kn.cheksumURL = \"${new_checksum_url}\"' src/tools.json  > src/tools.json.new
          mv src/tools.json.new src/tools.json
          checksum=`curl -s ${new_url}.sha256`
          for platform in win32 darwin linux; do
            old_url=`jq -r .kn.platform.${platform}.url src/tools.json`
            new_url=`echo ${old_url} | sed "s|${{ env.REPO_KN_CLIENT_VERSION }}|${{ env.LATEST_TOOL_RELEASE }}|"`

            jq --indent 4 ".kn.platform.${platform}.url = \"${new_url}\"" src/tools.json | jq --indent 4 ".kn.platform.${platform}.sha256sum = \"${checksum}\"" > src/tools.json.new
            mv src/tools.json.new src/tools.json
          done
      - name: Create pull request
        if: ${{ (env.LATEST_TOOL_RELEASE != env.REPO_KN_CLIENT_VERSION) && (env.PR_EXISTS == 0) }}
        run: |
          git config --global user.email "openshifttools-bot@users.noreply.github.com"
          git config --global user.name "openshifttools-bot"
          git checkout -b "kn-client-${{ env.LATEST_TOOL_RELEASE }}"
          git commit -am "Update kn client to ${{ env.LATEST_TOOL_RELEASE }}"
          git push origin "kn-client-${{ env.LATEST_TOOL_RELEASE }}"
          gh pr create --title "Update kn client to ${{ env.LATEST_TOOL_RELEASE }}" --body "See ${{ env.LATEST_TOOL_URL }}"
