name: Check for cycles in modules

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cyclesCheck:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v7

      # Set up Node
      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24

      # Run install dependencies
      - name: Install dependencies
        run: |
          npm ci --ignore-scripts
          npm rebuild cpu-features ssh2

      - name: Check cycles
        run : npm run check-cycles
